baseurl: ""
url: "https://scorpion-coders.netlify.com/" 
markdown: kramdown
exclude: [README.md, gemfile, gemfile.lock, _dist, package.json, package-lock.json]
permalink: none
destination: _dist
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
